sudo: required

language: ruby

services:
  - docker

branches:
  only:
    - develop 

before_install:
  - pwd
  - ls -sort
  - cd ..
  - mv travis_test CARTAvis
  - cd CARTAvis
  - ls -sort
  - pwd
  - echo $PWD
  - docker pull ajmasiaa/centos7-carta-server-18-10-2017
  - docker ps -a
  - docker run --name carta_build -v $PWD:/cartabuild/CARTAvis -dit ajmasiaa/centos7-carta-server-18-10-2017
  - docker exec -it carta_build bash -l
  - docker exec -it carta_build ./cartabuild/CARTAvis/carta/html5/common/skel/generate.py source-all > /dev/null && mkdir /cartabuild/CARTAvis/build && cd /cartabuild/CARTAvis/build && export PATH=/opt/Qt/5.3/gcc_64/bin:$PATH && make -j 2

