sudo: required

language: ruby

services:
  - docker

branches:
  only:
    - develop 

before_install:
  - pwd
  - ls -sort
  - cd ..
  - mv travis_test CARTAvis
  - cd CARTAvis
  - ls -sort
  - pwd
  - echo $PWD
  - docker pull ajmasiaa/centos7-carta-server-18-10-2017
  - docker ps -a
  - docker run -ti -v $PWD:/cartabuild/CARTAvis ajmasiaa/centos7-carta-server-18-10-2017 /bin/sh -c "/cartabuild/CARTAvis/run.sh"

