# .travis-ci script to build Linux version of CARTA using a docker image

sudo: required
os: osx
language: ruby

services:
  - docker

before_install:
  - docker pull ajmasiaa/centos7-carta-server-18-10-2017
  - docker run -d -p 127.0.0.1:80:4567 -v $HOME/build/CARTAvis:/cartabuild/CARTAvis ajmasiaa/centos7-carta-server-18-10-2017
  - docker ps -a

script:
  - echo "Building CARTA"
  - export PATH=/opt/Qt/5.3/gcc_64/bin:$PATH
  - cd /cartabuild/CARTAvis/carta/html5/common/skel
  - ./generate.py source-all > /dev/null
  - mkdir /cartabuild/CARTAvis/build
  - cd /cartabuild/CARTAvis/build
  - qmake CARTA_BUILD_TYPE=dev ../carta -r
  - make -j 2


