sudo: required

language: ruby

services:
  - docker

branches:
  only:
    - develop 

before_install:
  - pwd
  - ls -sort
  - cd ..
  - mv travis_test CARTAvis
  - cd CARTAvis
  - ls -sort
  - pwd
  - echo $PWD
  - docker pull ajmasiaa/centos7-carta-server-18-10-2017
  - docker ps -a
  - docker run -ti -v $PWD:/cartabuild/CARTAvis ajmasiaa/centos7-carta-server-18-10-2017 /bin/sh -c "chmod 755 /cartabuild/CARTAvis/run.sh && /cartabuild/CARTAvis/run.sh"

script:
  - cd $HOME/build/ajm-asiaa/CARTAvis/build
  - ls -sort
  - sudo mv carta-centos7-test.tar.gz Carta.dmg
  - sudo git clone https://github.com/CARTAvis/gdrive_uploader.git
  - ls
#  - sudo chmod -R 777 gdrive_uploader
  - cd gdrive_uploader
  - ls
  - node --version
  - sudo npm install
  - sudo npm start

