sudo: required

language: ruby

services:
  - docker

branches:
  only:
    - develop 

before_install:
  - pwd
  - ls -sort
  - cd ..
  - mv travis_test CARTAvis
  - cd CARTAvis
  - ls -sort
  - pwd
  - echo $PWD
  - docker pull ajmasiaa/centos7-carta-server-18-10-2017
  - docker ps -a
#  - docker run -d -p 8080:8080 -v $PWD:/cartabuild/CARTAvis ajmasiaa/centos7-carta-server-18-10-2017
#  - docker run -ti -v $PWD:/cartabuild/CARTAvis ajmasiaa/centos7-carta-server-18-10-2017
  - docker run --name carta_build -v $PWD:/cartabuild/CARTAvis -dit ajmasiaa/centos7-carta-server-18-10-2017
  - docker exec -it carta_build bash -l
  - su - travis
  - ls
  - cd /cartabuild/CARTAvis
  - ls
#  - docker ps -a
#  - docker run ajmasiaa/centos7-carta-server-18-10-2017 /bin/sh -c "ls"
#  - docker run ajmasiaa/centos7-carta-server-18-10-2017 /bin/sh -c "cd cartabuild"
#  - docker run ajmasiaa/centos7-carta-server-18-10-2017 /bin/sh -c "ls"
#  - docker run ajmasiaa/centos7-carta-server-18-10-2017 /bin/sh -c "cd CARTAvis"
#  - docker run ajmasiaa/centos7-carta-server-18-10-2017 /bin/sh -c "ls"
#  - docker run ajmasiaa/centos7-carta-server-18-10-2017 /bin/sh -c "export PATH=/opt/Qt/5.3/gcc_64/bin:$PATH"
#  - docker run ajmasiaa/centos7-carta-server-18-10-2017 /bin/sh -c "./cartabuild/CARTAvis/carta/html5/common/skel/generate.py source-all > /dev/null"
#  - docker run ajmasiaa/centos7-carta-server-18-10-2017 /bin/sh -c "mkdir /cartabuild/CARTAvis/build"
#  - docker run ajmasiaa/centos7-carta-server-18-10-2017 /bin/sh -c "cd /cartabuild/CARTAvis/build && qmake CARTA_BUILD_TYPE=dev ../carta -r"
#  - docker run ajmasiaa/centos7-carta-server-18-10-2017 /bin/sh -c "cd /cartabuild/CARTAvis/build && make -j 2"

script:
  - ls -sort

